{
  "headers": {
    "x-correlation-id": "123",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.44.1",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "717439c3-8e06-4ca2-860d-12a10a5f2a6b",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "215"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/facebook",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/facebook",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/facebook",
  "uriParams": {},
  "rawRequestUri": "/api/facebook",
  "rawRequestPath": "/api/facebook",
  "remoteAddress": "/127.0.0.1:65132",
  "requestPath": "/api/facebook"
}